- name: Install nova usage pip packages (venv)
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ nova_venv_dir }}"
    virtualenv_site_packages: "no"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ nova_usage_pip_packages }}"
  when:
    - nova_venv_enabled | bool
  notify:
    - Restart nova api
  tags:
    - nova-usage-install
    - nova-usage-install-pip-packages

- name: Install nova usage pip packages (no venv)
  pip:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ nova_usage_pip_packages }}"
  when:
    - not nova_venv_enabled | bool
  notify:
    - Restart nova api
  tags:
    - nova-usage-install
    - nova-usage-install-pip-packages
