- name: Create /etc/os_usage
  file:
    path: /etc/os_usage
    state: directory

- name: Drop /etc/os_usage/cinder.yml
  template:
    src: cinder.yml.j2
    dest: /etc/os_usage/cinder.yml
    mode: "0644"
    owner: "root"
    group: "root"
  notify:
    - Restart cinder api

- name: Install cinder usage pip packages (venv)
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ cinder_venv_dir }}"
    virtualenv_site_packages: "no"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ cinder_usage_pip_packages }}"
  when:
    - cinder_venv_enabled | bool
  notify:
    - Restart cinder api
  tags:
    - cinder-usage-install
    - cinder-usage-install-pip-packages

- name: Install cinder usage pip packages (no venv)
  pip:
    name: "{{ item }}"
    state: present
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items:
    - "{{ cinder_usage_pip_packages }}"
  when:
    - not cinder_venv_enabled | bool
  notify:
    - Restart cinder api
  tags:
    - cinder-usage-install
    - cinder-usage-install-pip-packages

- name: Stat sitecutomize.py (venv)
  stat:
    path: "{{ cinder_venv_dir }}/lib/python2.7/sitecustomize.py"
  register: sitecustomize_venv_stat
  when:
    - cinder_venv_enabled | bool

- name: Stat sitecustomize.py (no venv)
  stat:
    path: /etc/python2.7/sitecustomize.py
  register: sitecustomize_stat
  when:
    - not cinder_venv_enabled | bool

- name: Drop sitecustomize.py (venv)
  template:
    src: sitecustomize.py.j2
    dest: "{{ cinder_venv_dir }}/lib/python2.7/sitecustomize.py"
    mode: "0644"
    owner: "root"
    group: "root"
  when:
    - cinder_venv_enabled | bool
    - not sitecustomize_venv_stat.stat.exists
  notify:
    - Restart cinder api

- name: Drop sitecustomize.py (no venv)
  template:
    src: sitecustomize.py.j2
    dest: /etc/python2.7/sitecustomize.py
    mode: "0644"
    owner: "root"
    group: "root"
  when:
    - not cinder_venv_enabled | bool
    - not sitecustomize_stat.stat.exists
  notify:
    - Restart cinder api
